app:
  jwt:
    access-secret: ${JWT_ACCESS_SECRET}
    refresh-secret: ${JWT_REFRESH_SECRET}
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173

spring:
  data:
    redis:
      repositories:
        enabled: false
